name: GUIAPI
version: 1.0.2
description: An API/Library Plugin for Menus/GUIs (doesn’t do much on its own).
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.GUIAPI.GUIAPI
commands:
   toggleTestMode:
      description: Toggles whether debug messages are on (only use if you know what you’re doing)
      usage: /<command>
      permission: GUIAPI.toggletestmode
      permission-message: You don't have permission

permissions:
   GUIAPI.*:
        description: Gives access to all GUIAPI permissions
   GUIAPI.toggletestmode:
      description: Toggles whether debug messages are on (only use if you know what you’re doing)